build: main.cpp utility.cpp utility.h
	@echo "Compiling Code"
	g++ main.cpp utility.cpp -o todolist
	@echo "Compiling Complete"
	
	
run: todolist
	./todolist


clean: todolist
	rm todolist
	@echo "todolist program removed"
	

